# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# compile C with D:/CLion 2025.1.1/bin/mingw/bin/gcc.exe
# compile CXX with D:/CLion 2025.1.1/bin/mingw/bin/g++.exe
C_DEFINES = -DMINGW_HAS_SECURE_API=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NEEDS_QMAIN -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64

C_INCLUDES = @CMakeFiles/app_gui.dir/includes_C.rsp

C_FLAGS = -fdiagnostics-color=always

CXX_DEFINES = -DMINGW_HAS_SECURE_API=1 -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NEEDS_QMAIN -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DUNICODE -DWIN32 -DWIN64 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64

CXX_INCLUDES = @CMakeFiles/app_gui.dir/includes_CXX.rsp

CXX_FLAGS = -std=gnu++20 -fdiagnostics-color=always

