# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# compile C with D:/CLion 2025.1.1/bin/mingw/bin/gcc.exe
# compile CXX with D:/CLion 2025.1.1/bin/mingw/bin/g++.exe
C_DEFINES = 

C_INCLUDES = @CMakeFiles/app_console.dir/includes_C.rsp

C_FLAGS = -fdiagnostics-color=always

CXX_DEFINES = 

CXX_INCLUDES = @CMakeFiles/app_console.dir/includes_CXX.rsp

CXX_FLAGS = -std=gnu++20 -fdiagnostics-color=always

